"""Capability-first composition primitives for YA Agent SDK."""

from ya_agent_sdk.capabilities.catalog import (
    ENTRY_POINT_GROUP,
    CapabilityCatalog,
    CapabilityRegistration,
    CapabilityTypeProvenance,
    CapabilityTypeReference,
    build_capability_catalog,
    discover_capability_types,
)
from ya_agent_sdk.capabilities.defaults import (
    BUILTIN_CAPABILITY_TYPES,
    build_default_capability_catalog,
)
from ya_agent_sdk.capabilities.features import (
    DocumentConversionCapability,
    FilesystemCapability,
    MediaReadCapability,
    NoteCapability,
    ShellCapability,
    SkillsCapability,
    TaskCapability,
    ThinkingCapability,
    ToolProxyCapability,
    UserInteractionCapability,
    WebContentCapability,
    WebSearchCapability,
)
from ya_agent_sdk.capabilities.foundation import (
    ColdStartCapability,
    ContextCompactionCapability,
    DeferredTerminalCapability,
    EnvironmentContextCapability,
    FileInspectionCapability,
    HandoffCapability,
    MediaCompatibilityCapability,
    OverallRetryBudget,
    ReasoningCompatibilityCapability,
    RuntimeContextCapability,
    SupportsDeferredOutput,
    ToolArgumentRepairCapability,
    ToolIdCompatibilityCapability,
)
from ya_agent_sdk.capabilities.plugins import (
    CAPABILITY_PLUGIN_SCHEMA_VERSION,
    CapabilityPluginGrant,
    CapabilityPluginManifest,
    ResolvedCapabilityPlugins,
    load_capability_plugin_manifest,
    load_capability_plugins,
    resolve_capability_plugins,
)
from ya_agent_sdk.capabilities.presets import RuntimeFoundationCapability
from ya_agent_sdk.capabilities.tool_policy import (
    ToolApprovalCapability,
    ToolObservationCapability,
    ToolSupersessionCapability,
    ToolTimeoutCapability,
    ToolVisibilityCapability,
)
from ya_agent_sdk.codeact import CodeActCapability

__all__ = [
    "BUILTIN_CAPABILITY_TYPES",
    "CAPABILITY_PLUGIN_SCHEMA_VERSION",
    "ENTRY_POINT_GROUP",
    "CapabilityCatalog",
    "CapabilityPluginGrant",
    "CapabilityPluginManifest",
    "CapabilityRegistration",
    "CapabilityTypeProvenance",
    "CapabilityTypeReference",
    "CodeActCapability",
    "ColdStartCapability",
    "ContextCompactionCapability",
    "DeferredTerminalCapability",
    "DocumentConversionCapability",
    "EnvironmentContextCapability",
    "FileInspectionCapability",
    "FilesystemCapability",
    "HandoffCapability",
    "MediaCompatibilityCapability",
    "MediaReadCapability",
    "NoteCapability",
    "OverallRetryBudget",
    "ReasoningCompatibilityCapability",
    "ResolvedCapabilityPlugins",
    "RuntimeContextCapability",
    "RuntimeFoundationCapability",
    "ShellCapability",
    "SkillsCapability",
    "SupportsDeferredOutput",
    "TaskCapability",
    "ThinkingCapability",
    "ToolApprovalCapability",
    "ToolArgumentRepairCapability",
    "ToolIdCompatibilityCapability",
    "ToolObservationCapability",
    "ToolProxyCapability",
    "ToolSupersessionCapability",
    "ToolTimeoutCapability",
    "ToolVisibilityCapability",
    "UserInteractionCapability",
    "WebContentCapability",
    "WebSearchCapability",
    "build_capability_catalog",
    "build_default_capability_catalog",
    "discover_capability_types",
    "load_capability_plugin_manifest",
    "load_capability_plugins",
    "resolve_capability_plugins",
]
