"""Capability-first composition primitives for YA Agent SDK."""

from ya_agent_sdk.capabilities.catalog import (
    ENTRY_POINT_GROUP,
    CapabilityCatalog,
    CapabilityRegistration,
    build_capability_catalog,
)
from ya_agent_sdk.capabilities.features import (
    DocumentConversionCapability,
    FilesystemCapability,
    MediaReadCapability,
    NoteCapability,
    ShellCapability,
    SkillsCapability,
    TaskCapability,
    ThinkingCapability,
    TodoCapability,
    ToolProxyCapability,
    UserInteractionCapability,
    WebContentCapability,
    WebSearchCapability,
)
from ya_agent_sdk.capabilities.foundation import (
    ColdStartCapability,
    ContextCompactionCapability,
    DeferredTerminalCapability,
    EnvironmentContextCapability,
    FileInspectionCapability,
    HandoffCapability,
    MediaCompatibilityCapability,
    OverallRetryBudget,
    ReasoningCompatibilityCapability,
    RuntimeContextCapability,
    ToolArgumentRepairCapability,
    ToolIdCompatibilityCapability,
)
from ya_agent_sdk.capabilities.presets import (
    ModelCompatibilityCapability,
    RuntimeFoundationCapability,
    ToolCallCompatibilityCapability,
)
from ya_agent_sdk.capabilities.tool_policy import (
    ToolApprovalCapability,
    ToolExecutionPolicyCapability,
    ToolObservationCapability,
    ToolRetryCapability,
    ToolTimeoutCapability,
    ToolVisibilityCapability,
)
from ya_agent_sdk.codeact import CodeActCapability

BUILTIN_CAPABILITY_TYPES = (
    CodeActCapability,
    ColdStartCapability,
    ContextCompactionCapability,
    DeferredTerminalCapability,
    DocumentConversionCapability,
    EnvironmentContextCapability,
    FileInspectionCapability,
    FilesystemCapability,
    HandoffCapability,
    MediaCompatibilityCapability,
    MediaReadCapability,
    ModelCompatibilityCapability,
    NoteCapability,
    OverallRetryBudget,
    ReasoningCompatibilityCapability,
    RuntimeContextCapability,
    RuntimeFoundationCapability,
    ShellCapability,
    SkillsCapability,
    TaskCapability,
    ThinkingCapability,
    TodoCapability,
    ToolApprovalCapability,
    ToolArgumentRepairCapability,
    ToolCallCompatibilityCapability,
    ToolExecutionPolicyCapability,
    ToolIdCompatibilityCapability,
    ToolObservationCapability,
    ToolRetryCapability,
    ToolTimeoutCapability,
    ToolVisibilityCapability,
    UserInteractionCapability,
    WebContentCapability,
    WebSearchCapability,
)


def build_default_capability_catalog(
    *,
    explicit_types=(),
    selected_entry_points=(),
) -> CapabilityCatalog:
    """Build the SDK catalog with all built-in serializable capability types."""
    return build_capability_catalog(
        sdk_types=BUILTIN_CAPABILITY_TYPES,
        explicit_types=explicit_types,
        selected_entry_points=selected_entry_points,
    )


__all__ = [
    "BUILTIN_CAPABILITY_TYPES",
    "ENTRY_POINT_GROUP",
    "CapabilityCatalog",
    "CapabilityRegistration",
    "CodeActCapability",
    "ColdStartCapability",
    "ContextCompactionCapability",
    "DeferredTerminalCapability",
    "DocumentConversionCapability",
    "EnvironmentContextCapability",
    "FileInspectionCapability",
    "FilesystemCapability",
    "HandoffCapability",
    "MediaCompatibilityCapability",
    "MediaReadCapability",
    "ModelCompatibilityCapability",
    "NoteCapability",
    "OverallRetryBudget",
    "ReasoningCompatibilityCapability",
    "RuntimeContextCapability",
    "RuntimeFoundationCapability",
    "ShellCapability",
    "SkillsCapability",
    "TaskCapability",
    "ThinkingCapability",
    "TodoCapability",
    "ToolApprovalCapability",
    "ToolArgumentRepairCapability",
    "ToolCallCompatibilityCapability",
    "ToolExecutionPolicyCapability",
    "ToolIdCompatibilityCapability",
    "ToolObservationCapability",
    "ToolProxyCapability",
    "ToolRetryCapability",
    "ToolTimeoutCapability",
    "ToolVisibilityCapability",
    "UserInteractionCapability",
    "WebContentCapability",
    "WebSearchCapability",
    "build_capability_catalog",
    "build_default_capability_catalog",
]
